# Python Script to automatically calculate data for factsheet

In [57]:
## Part 1. Import necessary stuff

In [58]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
from datetime import date
import check_month as cm

In [59]:
## Part 2. Read file from DataFrame

In [60]:
index_value_DF = pd.read_excel('Z:/book1.xlsx', 'Sheet1', index_col=0, na_values=['NA'])
style.use('ggplot')

index_value_DF['VN30'].plot()

print(index_value_DF.head())

              VN30    VNMidcap  VNSmallcap       VN100  VNAllshare  VNINDEX
Ngày
2009-01-02  313.34  226.800443  431.680524  279.635396  292.559643   313.34
2009-01-05  311.23  225.606147  433.071975  278.073636  290.991059   311.91
2009-01-06  314.21  227.755880  440.869613  281.259627  294.361648   314.04
2009-01-07  320.53  231.874391  448.625920  287.622684  300.981447   319.58
2009-01-08  314.14  229.312083  440.731845  282.571505  295.696812   314.15

In [61]:
index_value_DF.keys()

Index(['VN30', 'VNMidcap', 'VNSmallcap', 'VN100', 'VNAllshare', 'VNINDEX'], dtype='object')

In [62]:
begin = cm.mkFirstOfMonth(cm.mkDateTime("2016-01-03"))
end = cm.mkLastOfMonth(cm.mkDateTime("2016-02-03"))

In [63]:
index_value_DF[begin:end]

              VN30  VNMidcap  VNSmallcap   VN100  VNAllshare  VNINDEX
Ngày
2016-01-04  589.91    735.89      686.57  569.10      569.10   574.41
2016-01-05  583.62    731.05      683.84  563.84      563.84   569.94
2016-01-06  589.97    735.65      687.61  569.18      569.18   574.57
2016-01-07  582.30    724.74      678.22  562.36      562.36   565.36
2016-01-08  575.96    719.20      666.14  556.70      556.70   560.05
2016-01-11  573.72    712.12      662.07  553.87      553.87   557.87
2016-01-12  582.39    724.00      669.82  561.95      561.95   564.26
2016-01-13  578.63    723.08      666.69  558.67      558.67   560.37
2016-01-14  569.17    715.45      659.58  550.95      550.95   553.03
2016-01-15  555.76    709.35      655.54  539.96      539.96   543.04
2016-01-18  541.18    692.97      642.43  526.99      526.99   526.37
2016-01-19  550.29    703.11      650.28  535.27      535.27   535.77
2016-01-20  544.24    697.85      647.61  530.07      530.07   544.24
2016-01-21  538.53    693.08      641.18  525.46      525.46   521.88
2016-01-22  539.37    697.80      643.11  526.59      526.59   522.24
2016-01-25  562.19    715.93      660.36  545.80      545.80   542.35
2016-01-26  554.52    707.98      653.42  538.66      538.66   537.73
2016-01-27  558.98    714.25      658.18  542.89      542.89   542.69
2016-01-28  556.86    710.65      653.91  540.94      540.94   539.47
2016-01-29  561.61    716.72      659.64  544.92      544.92   545.25
2016-02-01  557.98    711.31      656.42  541.66      541.66   540.56
2016-02-02  555.09    709.29      652.67  539.32      539.32   536.45
2016-02-03  556.53    710.09      654.72  540.80      540.80   539.07
2016-02-04  561.22    714.64      659.31  544.99      544.99   542.15
2016-02-05  563.97    720.55      666.01  548.07      548.07   544.75
2016-02-15  559.19    723.13      667.67  545.24      545.24   543.79
2016-02-16  562.32    732.38      674.13  549.40      549.40   548.05
2016-02-17  561.10    732.65      676.83  548.92      548.92   547.05
2016-02-18  566.85    737.04      681.85  553.56      553.56   552.49
2016-02-19  567.51    739.14      682.56  554.03      554.03   554.03
2016-02-22  574.37    747.35      687.80  560.47      560.47   560.71
2016-02-23  573.78    746.85      687.44  560.11      560.11   561.28
2016-02-24  578.87    748.03      688.28  563.70      563.70   568.04
2016-02-25  573.02    743.09      684.00  558.58      558.58   562.82
2016-02-26  577.71    745.65      689.59  562.22      562.22   566.11
2016-02-29  570.66    745.34      690.23  556.80      556.80   559.37

In [67]:
index_value_DF.corr()

                VN30  VNMidcap  VNSmallcap     VN100  VNAllshare   VNINDEX
VN30        1.000000  0.887575    0.456329  0.986277    0.971441  0.961386
VNMidcap    0.887575  1.000000    0.478689  0.931834    0.917378  0.921226
VNSmallcap  0.456329  0.478689    1.000000  0.550453    0.633214  0.615118
VN100       0.986277  0.931834    0.550453  1.000000    0.994332  0.983375
VNAllshare  0.971441  0.917378    0.633214  0.994332    1.000000  0.987369
VNINDEX     0.961386  0.921226    0.615118  0.983375    0.987369  1.000000